/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package example;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;
/**
 *
 * @author kevinsanchez
 */
public class calculator extends javax.swing.JFrame {
    String calculation = "";
    int solution;

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }
    
   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitle = new javax.swing.JLabel();
        jButtonnumber7 = new javax.swing.JButton();
        jButtonnumber8 = new javax.swing.JButton();
        jButtonnumber9 = new javax.swing.JButton();
        jButtonnumber4 = new javax.swing.JButton();
        jButtonnumber5 = new javax.swing.JButton();
        jButtonnumber6 = new javax.swing.JButton();
        jButtonnumber1 = new javax.swing.JButton();
        jButtonnumber2 = new javax.swing.JButton();
        jButtonnumber3 = new javax.swing.JButton();
        jButtonnumber0 = new javax.swing.JButton();
        jButtonpoint = new javax.swing.JButton();
        jButtonsolution = new javax.swing.JButton();
        jButtonparentesis1 = new javax.swing.JButton();
        jButtonparentesis2 = new javax.swing.JButton();
        jButtonpower = new javax.swing.JButton();
        jButtonrestart = new javax.swing.JButton();
        jButtondivision = new javax.swing.JButton();
        jButtonmulty = new javax.swing.JButton();
        jButtonsubstrac = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitle.setText("Calculator");

        jButtonnumber7.setText("7");
        jButtonnumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber7ActionPerformed(evt);
            }
        });

        jButtonnumber8.setText("8");
        jButtonnumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber8ActionPerformed(evt);
            }
        });

        jButtonnumber9.setText("9");
        jButtonnumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber9ActionPerformed(evt);
            }
        });

        jButtonnumber4.setText("4");
        jButtonnumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber4ActionPerformed(evt);
            }
        });

        jButtonnumber5.setText("5");
        jButtonnumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber5ActionPerformed(evt);
            }
        });

        jButtonnumber6.setText("6");
        jButtonnumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber6ActionPerformed(evt);
            }
        });

        jButtonnumber1.setText("1");
        jButtonnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber1ActionPerformed(evt);
            }
        });

        jButtonnumber2.setText("2");
        jButtonnumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber2ActionPerformed(evt);
            }
        });

        jButtonnumber3.setText("3");
        jButtonnumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber3ActionPerformed(evt);
            }
        });

        jButtonnumber0.setText("0");
        jButtonnumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnumber0ActionPerformed(evt);
            }
        });

        jButtonpoint.setText(".");
        jButtonpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpointActionPerformed(evt);
            }
        });

        jButtonsolution.setText("=");
        jButtonsolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsolutionActionPerformed(evt);
            }
        });

        jButtonparentesis1.setText("(");
        jButtonparentesis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonparentesis1ActionPerformed(evt);
            }
        });

        jButtonparentesis2.setText(")");
        jButtonparentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonparentesis2ActionPerformed(evt);
            }
        });

        jButtonpower.setText("^");
        jButtonpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpowerActionPerformed(evt);
            }
        });

        jButtonrestart.setText("AC");

        jButtondivision.setBackground(new java.awt.Color(255, 255, 255));
        jButtondivision.setText("/");
        jButtondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondivisionActionPerformed(evt);
            }
        });

        jButtonmulty.setText("*");
        jButtonmulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmultyActionPerformed(evt);
            }
        });

        jButtonsubstrac.setText("-");
        jButtonsubstrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubstracActionPerformed(evt);
            }
        });

        jButtonadd.setText("+");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        screen.setColumns(20);
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonnumber1)
                            .addComponent(jButtonnumber0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonnumber2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonnumber3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonpoint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonsolution)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonadd)
                            .addComponent(jButtonsubstrac)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonnumber4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonnumber5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonnumber6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonmulty))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonnumber7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonnumber8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonnumber9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonparentesis1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonparentesis2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonpower)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtondivision)
                            .addComponent(jButtonrestart)))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonparentesis1)
                    .addComponent(jButtonparentesis2)
                    .addComponent(jButtonpower)
                    .addComponent(jButtonrestart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnumber7)
                    .addComponent(jButtonnumber8)
                    .addComponent(jButtonnumber9)
                    .addComponent(jButtondivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnumber4)
                    .addComponent(jButtonnumber5)
                    .addComponent(jButtonnumber6)
                    .addComponent(jButtonmulty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnumber1)
                    .addComponent(jButtonnumber2)
                    .addComponent(jButtonnumber3)
                    .addComponent(jButtonsubstrac))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonsolution)
                    .addComponent(jButtonpoint)
                    .addComponent(jButtonnumber0)
                    .addComponent(jButtonadd)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsolutionActionPerformed
        // TODO add your handling code here:
        ScriptEngineManager em = new ScriptEngineManager();
        ScriptEngine manager = em.getEngineByName("Javascript");
        try {
            solution = (int) manager.eval(calculation);
        } catch (ScriptException ex) {
            Logger.getLogger(calculator.class.getName()).log(Level.SEVERE, null, ex);
        }
        screen.setText(solution+" ");
    }//GEN-LAST:event_jButtonsolutionActionPerformed

    private void jButtonsubstracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubstracActionPerformed
        // TODO add your handling code here:
        calculation += jButtonsubstrac.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonsubstracActionPerformed

    private void jButtonnumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber0ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber0.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber0ActionPerformed

    private void jButtonnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber1ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber1.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber1ActionPerformed

    private void jButtonnumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber2ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber2.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber2ActionPerformed

    private void jButtonnumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber3ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber3.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber3ActionPerformed

    private void jButtonnumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber4ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber4.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber4ActionPerformed

    private void jButtonnumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber5ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber5.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber5ActionPerformed

    private void jButtonnumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber6ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber6.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber6ActionPerformed

    private void jButtonnumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber7ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber7.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber7ActionPerformed

    private void jButtonnumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber8ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber8.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber8ActionPerformed

    private void jButtonnumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnumber9ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonnumber9.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonnumber9ActionPerformed

    private void jButtonpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpointActionPerformed
        // TODO add your handling code here:
        calculation += jButtonpoint.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonpointActionPerformed

    private void jButtonparentesis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonparentesis1ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonparentesis1.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonparentesis1ActionPerformed

    private void jButtonparentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonparentesis2ActionPerformed
        // TODO add your handling code here:
        calculation += jButtonparentesis2.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonparentesis2ActionPerformed

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        // TODO add your handling code here:
        calculation += jButtonadd.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtonmultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmultyActionPerformed
        // TODO add your handling code here:
        calculation += jButtonmulty.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonmultyActionPerformed

    private void jButtondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondivisionActionPerformed
        // TODO add your handling code here:
        calculation += jButtondivision.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtondivisionActionPerformed

    private void jButtonpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpowerActionPerformed
        // TODO add your handling code here:
        calculation += jButtonpower.getText();
        screen.setText(calculation);
    }//GEN-LAST:event_jButtonpowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtondivision;
    private javax.swing.JButton jButtonmulty;
    private javax.swing.JButton jButtonnumber0;
    private javax.swing.JButton jButtonnumber1;
    private javax.swing.JButton jButtonnumber2;
    private javax.swing.JButton jButtonnumber3;
    private javax.swing.JButton jButtonnumber4;
    private javax.swing.JButton jButtonnumber5;
    private javax.swing.JButton jButtonnumber6;
    private javax.swing.JButton jButtonnumber7;
    private javax.swing.JButton jButtonnumber8;
    private javax.swing.JButton jButtonnumber9;
    private javax.swing.JButton jButtonparentesis1;
    private javax.swing.JButton jButtonparentesis2;
    private javax.swing.JButton jButtonpoint;
    private javax.swing.JButton jButtonpower;
    private javax.swing.JButton jButtonrestart;
    private javax.swing.JButton jButtonsolution;
    private javax.swing.JButton jButtonsubstrac;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea screen;
    // End of variables declaration//GEN-END:variables
}
